name: Greeting Workflow

on:
  push:
    paths:
      - '.github/workflows/Deploymedist.yaml'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the World
        run: echo "Hello, World!"
